Fix cluster status update
Status update somehow worked even without converting string to
ClusterStatus, but it doesn't work now. It seems that string value is no
longer auto-converted to ClusterStatus by SQLAlchemy, the error is:

```
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation)
invalid input value for enum clusterstatus: "Active"
LINE 1: UPDATE lab_cluster SET status='Active' WHERE lab_cluster.id ...
```