Fix db upgrade
Merge branches and remove a double drop_index call.

```
flask_migrate[12] ERROR Error: Multiple head revisions are present for
given argument 'head'; please specify a specific target revision,
'<branchname>@head' to narrow to a specific head, or 'heads' for all
heads
```

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) index
"ix_lab_region_users_group" does not exist
```